/// Flutter icons PotokCustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PotokCustomIcons
///      fonts:
///       - asset: fonts/PotokCustomIcons.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class PotokCustomIcons {
  PotokCustomIcons._();

  static const _kFontFam = 'PotokCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData bell_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bubble_multi_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circled_profile_icon_bold = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database_script_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_sweep_fill0_wght700 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_icon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_icon_middle_rounded = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lines_chat_icon = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal_icon = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saving_filled = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saving_outlined = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
